export const userConstants = {
  USER_LIST_PROCESSING: "USER_LIST_PROCESSING",
  USER_LIST_SUCCESS: "USER_LIST_SUCCESS",
  USER_LIST_FAILURE: "USER_LIST_FAILURE",

  //USER_RULE_LIST_PROCESSING: "USER_RULE_LIST_PROCESSING",
  //USER_RULE_LIST_SUCCESS: "USER_RULE_LIST_SUCCESS",
  //USER_RULE_LIST_FAILURE: "USER_RULE_LIST_FAILURE",

  //USER_RULE_CREATE_PROCESSING: "USER_RULE_CREATE_PROCESSING",
  //USER_RULE_CREATE_SUCCESS: "USER_RULE_CREATE_SUCCESS",
  //USER_RULEL_CREATE_FAILURE: "USER_RULE_CREATE_FAILURE",

  //USER_RULE_DELETE_PROCESSING: "USER_RULE_DELETE_PROCESSING",
  //USER_RULE_DELETE_SUCCESS: "USER_RULE_DELETE_SUCCESS",
  //USER_RULE_DELETE_FAILURE: "USER_RULE_DELETE_FAILURE",

  USER_CREATE_PROCESSING: "USER_CREATE_PROCESSING",
  USER_CREATE_SUCCESS: "USER_CREATE_SUCCESS",
  USER_CREATE_FAILURE: "USER_CREATE_FAILURE"
};
